version: '3'

services:
  frontend:
    build: ./fe
    volumes:
      - ./fe:/app
      - /app/node_modules
    ports:
      - "8080:80"

  backend:
    build: ./be
    volumes:
      - ./be:/app
      - ./db:/sqlite_data
    ports:
      - "3030:3030"
    environment:
      - DSN=sqlite+aiosqlite:///sqlite_data/patch-em-all.sqlite
      - AUTH_SECRET=deez

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./fe/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  sqlite_data: