const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG'
const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG'
const OPEN_REGISTER_DIALOG = 'OPEN_REGISTER_DIALOG'
const CLOSE_REGISTER_DIALOG = 'CLOSE_REGISTER_DIALOG'
const CLIENT_LOGGED_IN = 'CLIENT_LOGGED_IN'
const OPEN_ADD_PATCH_DIALOG = 'OPEN_ADD_PATCH_DIALOG'
const CLOSE_ADD_PATCH_DIALOG = 'CLOSE_ADD_PATCH_DIALOG'

export default {
  OPEN_LOGIN_DIALOG: OPEN_LOGIN_DIALOG,
  CLOSE_LOGIN_DIALOG: CLOSE_LOGIN_DIALOG,
  OPEN_REGISTER_DIALOG: OPEN_REGISTER_DIALOG,
  CLOSE_REGISTER_DIALOG: CLOSE_REGISTER_DIALOG,
  CLIENT_LOGGED_IN: CLIENT_LOGGED_IN,
  OPEN_ADD_PATCH_DIALOG: OPEN_ADD_PATCH_DIALOG,
  CLOSE_ADD_PATCH_DIALOG: CLOSE_ADD_PATCH_DIALOG,
}
